### ISSUE TITLE
Major Error 20

### ISSUE THREAD

**Issue by acarrizosa** [wmay/dwnominate#10]
Hello,
I have successfully been able to run the dwnominate procedure on my data in the past.  At some point, however, the package has started crashing when trying to re-estimate the ideal points.  I have not changed my code or data really since the last time I ran the procedure, so I think there might have been an error in one of the updates.  

When I run the procedure in Windows, the package runs separate wnominate procedures for each legislative period to get the priors for dwnominate (previously the program ran a pooled OC to get the priors I think).  Then dwnominate proper starts running, and it starts estimating weights, betas, roll call vectors, but tends to crash on estimating legislator coordinates.  I ran the same code in linux to see if it worked there, and the same thing happens, but when I run dwnominate in linux I at least get a message that says "MAJOR ERROR 20".

I don't know if more people have been experiencing the same problem, but I wanted to make it known in case a solution can be found.  If you need me to provide more details about the issue please let me know how I can help.
Best,
Andy Carrizosa

**Comment by acarrizosa** [comment]
Attached is my replication code and the stored rollcall object:

[Replication Files.zip](https://github.com/wmay/dwnominate/files/3832972/Replication.Files.zip)

**Comment by acarrizosa** [comment]
Attached is my replication code and the stored rollcall object:
[Replication Files.zip](https://github.com/wmay/dwnominate/files/3832978/Replication.Files.zip)

**Comment by wmay** [comment]
I did change the default starting point estimation to match the procedure from Keith Poole's book "Spatial Models of Parliamentary Voting". However you can still get the OC results and pass those as the starting estimates, if that method works better for your data.

The obscure DW-NOMINATE error messages are one of the remaining parts of the fortran code that I haven't cleaned up for R yet. I can't say yet when that will happen.
