### ISSUE TITLE
Fortran errors aren't passed to R

### ISSUE THREAD

**Issue by wmay** [wmay/dwnominate#11]
Errors should be sent to R instead of terminating the session directly from fortran. See [Error signaling from Fortran](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Error-signaling-from-Fortran) in Writing R Extensions.

**Comment by davidaarmstrong** [comment]
Do you have any debugging suggestions for when R terminates when it gets to the `.Fortran` call?

**Comment by wmay** [comment]
I've used valgrind a few times to debug fortran issues but it can be pretty slow.

A lot of the time (but not every time) issues are caused by starting estimates that don't make much sense. DW-NOMINATE uses a local optimization algorithm to get a maximum likelihood estimate. The fortran code seems to not handle it very well when the  starting estimates aren't near the global maximum.

There are also obscure compilation issues from time to time. If you can run the package tests successfully then it helps to rule those out.

**Comment by wmay** [comment]
I should add, another way to test for compilation issues is to run the code on Linux. For whatever reason, there just don't seem to be compilation issues on Linux.
