### ISSUE TITLE
Weights Parameter Output

### ISSUE THREAD

**Issue by acarrizosa** [wmay/dwnominate#12]
Hello,
I'm writing with a question more than an issue exactly.  I'm wondering whether the outcome of your dwnominate procedure stores the estimated weight parameter anywhere.  I can't seem to find it.  I know that the default starting value for the weight parameter is w = 0.3463, and in the stored OC or common_space objects used as starting points I can also find the "fits" parameters which can be used for the weights as well, but both these values describe the starting points for the weights parameter, I think, and not the final weight parameter estimated by dwnominate. 

So my questions are two:
First, is the second dimension of the dwnominate output already weighted? That is, has results$legislators$coord2D already been multiplied by the output weight parameter?

Second, is there a way to find the output weight parameter after dwnominate has been carried out, or should I simply use results$start$fits to create weights after the estimation?

The main reason I am asking this is because I am trying to estimate cutting lines for the dwnominate estimates.  To do so both coord2D and certain bill-level parameters have to be multiplied by the weight parameter, and while looking through the code I was unsure whether coord2D was already multiplied by weights, and where the weight parameter can be found to multiply it by certain bill-level parameters.

Thank you and best,
Andy Carrizosa

**Comment by wmay** [comment]
No, the coordinates aren't weighted. They're the standard DW-NOMINATE coordinates, which are scaled to fit between -1 and 1 (more or less).

Right now the function doesn't return the weight parameter, but I agree that it should and it shouldn't be hard to add that feature. I'll see if I can do this in the next couple of days.

**Comment by acarrizosa** [comment]
I have been following the instructions laid out in the book "Analyzing Spatial Models of Choice and Judgment with R," written by Armstrong et al. (2014).  On pages 203-204 they show a procedure for estimating cutting lines that includes the use of the weight paramenter.

**Comment by acarrizosa** [comment]
Sorry to bother you again, but would it also be possible to make the function return the beta parameter as well when you modify it?

Thanks and best,
Andy

**Comment by wmay** [comment]
I'm returning the values in the same format as wnominate's nomObject, so with a bit of finagling the results can be used with `wnominate::plot.coords`:

```R
class(dwnom_result) <- "nomObject"
wnominate::plot.coords(dwnom_result)
```
