### ISSUE TITLE
Error:  $ operator is invalid for atomic vectors

### ISSUE THREAD

**Issue by hjlee87** [wmay/dwnominate#2]
Hello, 

This may be a very elementary-level question.. but I am trying to run dwnominate with a csv file and I keep getting that error message. Do you have any suggestions to fix this problem?

**Comment by wmay** [comment]
Hard to say without seeing the code.

The dwnominate function requires a list of rollcall objects, so if you pass it something else (say, a data frame from a csv), then you'll get errors like that.

I recommend taking a look at the [pscl documentation](https://cran.r-project.org/web/packages/pscl/pscl.pdf) where they describe rollcall objects, and the [tidyr](http://tidyr.tidyverse.org/) package for rearranging the data from your csv file.

You may also find the examples from the wnominate package useful -- [Scaling Roll Call Votes with wnominate in R](https://www.jstatsoft.org/article/view/v042i14). This was actually the first code I ever ran in R!

**Comment by hjlee87** [comment]
Thanks for your comment. But I am still experiencing the same problem. summary(rc) works fine but dwnominate(rc) gives me the same error as I posted above ($ operator is invalid for atomic vectors).


Below is the code I used:
------------------------------------------------------------------------------
library(wnominate)
library(dwnominate)
library(pscl)

ROK<-read.csv("ROK16_eng.csv", header=FALSE)
ROK<-as.matrix(ROK)
ROK<-as.data.frame(ROK)
ROK[1:5,1:6]

ROKnames<-ROK[,1]
legData<-data.frame(ROK[,2],length(ROK[,2]),1)
colnames(legData)<-"party"
ROK<-ROK[,-c(1,2)]
rc<-rollcall(ROK, yea=c(1), nay=c(2,3), missing=c(0), notInLegis=9, legis.names=ROKnames, legis.data=legData)

summary(rc)
dwnominate(rc)
---------------------------------------------------

I also checked is.atomic(rc) but the result is FALSE.

Do you have any other suggestions?

Thank you in advance.

**Comment by wmay** [comment]
Oh, I see. DW-NOMINATE is a dynamic model that analyzes multiple legislative sessions, so you need to pass it a list of rollcall objects in chronological order, one for each session. It doesn't work with only one rollcall object.

**Comment by hjlee87** [comment]
Oh thank you for your reply! I will try that!

**Comment by hjlee87** [comment]
I am having trouble merging separate rollcall objects per session (4 sessions in total) into a list of rollcall objects in chronological order. Is there a code to do this? I am not sure how to you would create the data w/ multiple legislative sessions.

**Comment by hjlee87** [comment]
So if I generate 4 separate rollcall objects (1 per session) using the code I posted above, is it okay to use the list() function to  create a list of multiple rollcall objects to run dwnominate?

**Comment by hjlee87** [comment]
I ran into another problem..

I am trying to run dwnominate on Windows but it shuts down before it can finish the estimation. 

![shutdown](https://user-images.githubusercontent.com/39392848/40278787-b1664bb6-5c72-11e8-9727-8f5bead29008.jpg)


Do you have any idea on how to fix this problem? Or is it a problem w/ my computer?

Thank you!

**Comment by wmay** [comment]
Do you get an error message? In the image you posted the function is running optimal classification to get starting values-- it hasn't even started DW-NOMINATE yet.

**Comment by wmay** [comment]
Try the example code with the senate dataset and let me know if that works for you.

**Comment by hjlee87** [comment]
It shuts down without any messages. I tried the example code with the senate data but that seems to work fine.

**Comment by wmay** [comment]
Based on your screenshot it looks like the issue occurs in the oc (optimal classification) function. I haven't run into issues with that so far so I'm not sure what the problem would be. Here are a couple of things I would check to start with:

- check your RAM usage when you run the function, to make sure you aren't running out of memory
- try running optimal classification with your original rollcall objects to make sure those are working correctly:
```
library(oc)
oc_results <- oc(rollcall_list[[1]])
# and then try the other 3
```

**Comment by hjlee87** [comment]
Thanks for your suggestion. I think it may be the RAM problem. I tried the oc command with each object but no problem there. But it does produce DWNOM objects (DWNOM21, 26, 28, 29, 40, and DW-NOMSTART, etc) and other files (rollcall_input, rollcall_output, rsort, etc) Is the final DWNOMINATE output in one of these files?

**Comment by jacksantucci** [comment]
I ran the algorithm several times on a Mac. I needed to do so in the command prompt instead of RGui. I don't know why. Memory seems as good as any likely explanation.

**Comment by wmay** [comment]
I tried it with the default windows GUI and I see that, yes, there is some very odd behavior.

Can you try running it in the windows cmd terminal? That worked normally for me. I was able to start R with
```
C:\"Program Files"\R\R-3.5.0\bin\R.exe
```

You should see more messages before it crashes.

The way I'm running fortran in this package goes against the official R package guidelines and leads to strange things in some circumstances.

**Comment by hjlee87** [comment]
Yes, it finally works. I think running it via RGui was the problem. Thank you very much for your help.

**Comment by wmay** [comment]
Good to know, I'll update the documentation to reflect that.
