### ISSUE TITLE
Running dwnominate on the Swedish parliament 

### ISSUE THREAD

**Issue by potmo** [wmay/dwnominate#24]
Hi, thanks for providing this good interface!

I'm working on running DW-NOMINATE on the Swedish parliament. I have the data and I'm able to convert it into the KH-format that seems to be what the fortran code consumes. I'm trying to get the the first and second DW-NOMINATE dimension of a particular legislator in relation to other legislators over time. I would also like to get the means for the different parties but that seems to be trivial since there are some prior art in the `plot` function in this repository. 

I should say that I've never wrote a line of R before but I do know a bunch of other languages so this might be (probably) a rookie question. Sorry. My goal here is to extract enough information so I can continue working in a language I'm more fluent in.

The results i get back from `dwnominate` seems to be to contain a `legislators`, `dimensions` and `rollcall` fields.
I can print the names along with the first dimension coordinate with `print(data.frame(name=results$legislators$name, coord=results$legislators$coord1D))`. That prints each legislator three times but they seem to have the same coordinates each time the legislator is printed. Can it really be that the legislators did not change their sentiment down to the tenth decimal over three years?

Also is there any way to get a higher resolution coordinates than per year? 

Sorry for the rambling question but I would bre really greatful if you could give me some pointers.

Just to get warmed up I tried some data on the US House just to see if everything is working.  
I use data from [https://legacy.voteview.com/house112.htm](https://legacy.voteview.com/house112.htm) and [https://legacy.voteview.com/house113.htm](https://legacy.voteview.com/house113.htm) for the 112th and 113th congress. 
The files I'm using looks like this:
```
1129991199 0USA     100  OBAMA      99999999999...
1122030041 1ALABAMA 20001BONNER     11161111116...
1122119241 2ALABAMA 20001ROBY       11161111116...
...
```

The entire code I'm using looks like this. Reading the KH files and converting it to `rollcall`-objects with `pscl` and then sending it into `dwnominate`:

```R
library(dwnominate)
library(pscl)

h111 = readKH("hou111kh.ord", desc="111th U.S. House")
h112 = readKH("hou112kh.ord", desc="112th U.S. House")
h113 = readKH("hou113kh.ord", desc="113th U.S. House")

results <- dwnominate(list(h111, h112, h113))
plot(results)

print(data.frame(name=results$legislators$name, coord=results$legislators$coord1D))
```

**Comment by wmay** [comment]
So it sounds like you had three sessions of data. For less than 5 sessions, if I recall correctly, only a constant model is fit. This is hardcoded in the fortran source code. For such a small number of sessions it's not clear that a more complicated model is a good idea.

Oh, you know what I should do-- I should just add a warning to let people know when that happens. 

Anyway, yes, you can get higher resolution coordinates. One approach would be to split the votes into more sessions. Another approach is interpolation-- the coordinates are just a polynomial fit to the session numbers (usually constant or linear), so interpolating is straightforward ~~and valid~~ and may or may not be valid, depending on the application. If you want a more flexible trajectory type, you'd have to look at some alternative methods like MQ scores for example

**Comment by potmo** [comment]
Thanks! Thats great! I'll try splitting the data into shorter session and I'll look into Martin-Quinn scores too. Seems like there is a C++ reference implementation for it.
