### ISSUE TITLE
Model stops due to missing variables

### ISSUE THREAD

**Issue by cdermont** [wmay/dwnominate#4]
Hi, and shortly a big thanks for your work! 

I've run into the issue that the new version you've put online around summer does require some variables in the `rollcall` object which was not necessary in earlier versions. As it is not documented which variables are required, other users might end up with the same problem, especially when applying the same model for other legislatures than the US. 

Notably, within `write_leg_file()` the procedure stops if you do not have rcl$state, rcl$icpsrState and rcl$cd (I suppose the same applies to other stuff which is, as I gather, not necessarily required for the model to compute voting position). As a workaround, I defined blank variables before creating the rollcall objects. However, a procedure which would not end up with an error might be more tangible, such as for example using `is.null()` instead of `is.na()` in lines 122-126:

`    all_state_nums = ifelsec(all_state_nums,
ifelse(is.null(rcl$icpsrState), 0, rcl$icpsrState))`

If not, I'd suggest documenting which variables are necessary so that users can adapt (not all countries have states, for example).

Thanks!

**Comment by wmay** [comment]
Thanks for the bug report and suggestion. It should be fixed now. Let me know if the new code works for you.
